const express = require('express');
const auth = require('../middlewares/authMiddleware');
const { getMe, updateMe, transacoes, enviar, getAll, getById } = require('../controllers/professorController');
const router = express.Router();
router.use(auth);
router.get('/me', getMe);
router.put('/me', updateMe);
router.get('/me/transacoes', transacoes);
router.post('/me/enviar/:alunoId', enviar);
router.get('/', getAll);
router.get('/:id', getById);
module.exports = router;