const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
dotenv.config();
const authRoutes = require('./routes/auth');
const alunoRoutes = require('./routes/aluno');
const professorRoutes = require('./routes/professor');
const parceiroRoutes = require('./routes/parceiro');
const vantagemRoutes = require('./routes/vantagem');
const transacaoRoutes = require('./routes/transacao');
const instituicaoRoutes = require('./routes/instituicao');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/auth', authRoutes);
app.use('/alunos', alunoRoutes);
app.use('/professores', professorRoutes);
app.use('/parceiros', parceiroRoutes);
app.use('/vantagens', vantagemRoutes);
app.use('/transacoes', transacaoRoutes);
app.use('/instituicoes', instituicaoRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));